# Generated by Django 3.2.4 on 2021-06-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nix', '0004_auto_20210622_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='valor',
            field=models.CharField(max_length=20),
        ),
    ]
