# Generated by Django 3.2.4 on 2021-06-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nix', '0005_alter_anuncio_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='imagem',
            field=models.ImageField(upload_to=''),
        ),
    ]
