# Generated by Django 3.2.4 on 2021-06-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nix', '0006_alter_anuncio_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='imagem',
            field=models.ImageField(upload_to='nix/'),
        ),
    ]
